### ISSUE TITLE
Need help with jruby openssl errors

### ISSUE THREAD

**Issue by atheiman** [jruby/jruby-openssl#141] opened 2017-09-22 03:24 UTC
Ive been doing [some work on the ruby_build chef cookbook](https://github.com/sous-chefs/ruby_build/pull/62#issuecomment-331304640) and having trouble with openssl on jruby-9.1.13.0 on centos 6, 7, and fedora latest.

Jruby seems to install just fine but not have a ca-bundle? [Basically, my failing test is checking the following](https://travis-ci.org/sous-chefs/ruby_build/jobs/278461649):

```
/usr/local/ruby/jruby-9.1.13.0/bin/ruby -rnet/http -e "Net::HTTP.get(URI('https://google.com'))"
exit_status should eq 0
```

If i run that on an instance, I get an error like:

```ruby
irb(main):003:0> Net::HTTP.get(URI('https://google.com'))
OpenSSL::SSL::SSLError: certificate verify failed
	from org/jruby/ext/openssl/SSLSocket.java:227:in `connect_nonblock'
	from /usr/local/ruby/jruby-9.1.7.0/lib/ruby/stdlib/net/http.rb:938:in `connect'
	from /usr/local/ruby/jruby-9.1.7.0/lib/ruby/stdlib/net/http.rb:868:in `do_start'
	from /usr/local/ruby/jruby-9.1.7.0/lib/ruby/stdlib/net/http.rb:857:in `start'
	from /usr/local/ruby/jruby-9.1.7.0/lib/ruby/stdlib/net/http.rb:585:in `start'
	from /usr/local/ruby/jruby-9.1.7.0/lib/ruby/stdlib/net/http.rb:480:in `get_response'
	from /usr/local/ruby/jruby-9.1.7.0/lib/ruby/stdlib/net/http.rb:457:in `get'
	from (irb):3:in `<eval>'
	from org/jruby/RubyKernel.java:1000:in `eval'
	from org/jruby/RubyKernel.java:1298:in `loop'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from /usr/local/ruby/jruby-9.1.7.0/bin/jirb:13:in `<main>'
```

Also, `OpenSSL::X509::DEFAULT_CERT_FILE` is `nil` when I launch `jirb` and `require 'openssl'`, even if I [`export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt`](https://stackoverflow.com/questions/5711190/how-to-get-rid-of-opensslsslsslerror)

Im just looking for anyway to make this test pass, but ideally the user shouldn't have to run a command before `ruby` to make openssl work

**Comment by atheiman** [comment] 2017-09-22 03:27
Maybe i should try java 7
https://github.com/docker-library/official-images/pull/391#issuecomment-70380235

**Comment by splattael** [comment] 2017-09-27 09:58
Hi,

we can reproduce @atheiman's error as well:

```
$ ruby -rnet/http -e 'p Net::HTTP.get_print(URI.parse("https://google.com/"))'
OpenSSL::SSL::SSLError: certificate verify failed
  connect_nonblock at org/jruby/ext/openssl/SSLSocket.java:228
           connect at /home/panadrwc/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:938
          do_start at /home/panadrwc/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:868
             start at /home/panadrwc/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:857
             start at /home/panadrwc/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:585
      get_response at /home/panadrwc/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:480
         get_print at /home/panadrwc/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:438
            <main> at -e:1
```


## JRuby

```
jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 Java HotSpot(TM) 64-Bit Server VM 25.112-b15 on 1.8.0_112-b15 +jit [linux-x86_64]
```

## Java

```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

## OS

```
$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
```

Note: It works on `CentOS Linux release 7.3.1611 (Core)`

**Comment by splattael** [comment] 2017-09-27 11:46
It seems that the Centos upgrade lost some certificates in `/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt`. Downgrading/restoring this bundle helped...

I wonder why it does it work on MRI but not on JRuby... Both, they should use the same bundle file?

**Comment by wakkowarner** [comment] 2017-09-27 12:05
_/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem_ dropped some SHA1 certificates. But I can't reproduce it with _cur --cacert_ with the newer certificate file...

**Comment by atheiman** [comment] 2017-09-27 14:28
a little more info here, i was just able to get this to work with a different url.

`letsencrypt.org` uses `Issuer: C=US, O=IdenTrust, OU=TrustID Server, CN=TrustID Server CA A52`

`www.google.com` uses `Issuer: C=US, O=Google Inc, CN=Google Internet Authority G2`

So yes it does seem like there is a change in the certs provided by the ca bundle.

```
[root@dokken ~]# /usr/local/ruby/jruby-9.1.13.0/bin/ruby -rnet/http -e "Net::HTTP.get(URI('https://www.google.com/'))"
OpenSSL::SSL::SSLError: certificate verify failed
  connect_nonblock at org/jruby/ext/openssl/SSLSocket.java:228
           connect at /usr/local/ruby/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:938
          do_start at /usr/local/ruby/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:868
             start at /usr/local/ruby/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:857
             start at /usr/local/ruby/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:585
      get_response at /usr/local/ruby/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:480
               get at /usr/local/ruby/jruby-9.1.13.0/lib/ruby/stdlib/net/http.rb:457
            <main> at -e:1
[root@dokken ~]# /usr/local/ruby/jruby-9.1.13.0/bin/ruby -rnet/http -e "Net::HTTP.get(URI('https://letsencrypt.org/'))"
[root@dokken ~]# echo $?
0
```

https://gist.github.com/atheiman/d044bccb4744309a02886bc6190c4ee0

**Comment by wakkowarner** [comment] 2017-09-28 09:57
It's the 1024 bit Equifax Secure CA certificate that was removed from the ca bundle that's causing the problem. Google's GeoTrust certificates are cross signed with that old Equifax cert.  See
https://www.mail-archive.com/openssl-dev@openssl.org/msg38674.html
for an explanation.
It looks like jruby is not stopping with validation at the GeoTrust certificate but - unnecessary - trying to validate against the Equifax root as well.

**Comment by andreaseger** [comment] 2017-10-19 12:23
Can anyone with knowledge about the insides of jruby-openssl have a look at this and make it work similar to standard openssl?
This is causing quite some issues for us but we do not have the inside knowledge about openssl/jruby-openssl to provide a fix ourselves.

**Comment by kares** [comment] 2021-04-10 17:55
closing as it's been confirmed to be a system CA issue

**Closed by kares** 2021-04-10 17:55 UTC
