### ISSUE TITLE
getting "Received fatal alert: bad_record_mac" in jruby 9.1.14.0

### ISSUE THREAD

**Issue by HoneyryderChuck** [jruby/jruby-openssl#151] opened 2017-11-22 16:49 UTC
I had this test working well under jruby-9.1.13.0 and jruby-openssl-0.9.21. I've just upgraded to 9.1.14.0, and it started failing, in this particular test I have with the ssl layer:

```
IOError: Received fatal alert: bad_record_mac
    org/jruby/ext/openssl/SSLSocket.java:836:in `sysread_nonblock'
    /user/.rubies/jruby-9.1.14.0/lib/ruby/stdlib/jopenssl23/openssl/buffering.rb:177:in `read_nonblock'
    /user/.rubies/jruby-9.1.14.0/lib/ruby/stdlib/net/protocol.rb:154:in `rbuf_fill'
```

I've ran the test using `JRUBY_OPTS="-J-Djavax.net.debug=ssl"` as well, of which I'll post the relevant part:

```
...
*** CertificateVerify
Signature Algorithm SHA512withRSA
main, WRITE: TLSv1.2 Handshake, length = 264
main, WRITE: TLSv1.2 Change Cipher Spec, length = 1
*** Finished
verify_data:  { 26, 20, 142, 172, 100, 32, 46, 83, 150, 55, 182, 45 }
***
main, WRITE: TLSv1.2 Handshake, length = 64
main, READ: TLSv1.2 Change Cipher Spec, length = 1
main, READ: TLSv1.2 Handshake, length = 64
*** Finished
verify_data:  { 235, 132, 199, 54, 76, 30, 161, 36, 33, 34, 246, 26 }
***
%% Cached client session: [Session-2, TLS_RSA_WITH_AES_128_CBC_SHA]
main, WRITE: TLSv1.2 Application Data, length = 105
main, READ: TLSv1.2 Alert, length = 48
main, RECV TLSv1.2 ALERT:  fatal, bad_record_mac
main, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
main, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
main, called closeOutbound()
main, closeOutboundInternal()
main, SEND TLSv1.2 ALERT:  warning, description = close_notify
main, WRITE: TLSv1.2 Alert, length = 48
```

Tell me if you need more troubleshooting info.

**Comment by HoneyryderChuck** [comment] 2017-11-22 17:00
This might be similar to the issue [reported here](https://github.com/jruby/jruby/issues/1331), as it's also file-size-dependent

**Comment by chhex** [comment] 2022-11-02 03:18
Same here : 
```
java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```

```
rbenv versions
  system
  2.6.6
  jruby-9.1.17.0
* jruby-9.3.6.0 (set by RBENV_VERSION environment variable)
```

```
gem push apscli-0.9.7-java.gem
Pushing gem to https://artifactory4t4apgsga.jfrog.io/artifactory/api/gems/apgGems...
ERROR:  While executing gem ... (IOError)
    Received fatal alert: bad_record_mac
```

I then downgraded to jruby-9.1.17.0 and that works.

**Comment by kares** [comment] 2024-04-26 09:53
seems to have been caused by limited cipher suite support, back in the day. closing as no longer relevant as there isn't much to be done here at this point.

**Closed by kares** 2024-04-26 09:53 UTC
