### ISSUE TITLE
Server Name Indication (SNI) Support

### ISSUE THREAD

**Issue by estolfo** [jruby/jruby-openssl#103] opened 2016-09-08 14:33 UTC
[This comment](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/SSLSocket.java#L180-L181) implies that SNI is supported but I'm not finding that it's the case.

I've been working on adding in TLS SNI support to the MongoDB driver and when on MRI, I can set the hostname on the SSLSocket after [this line](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/socket/ssl.rb#L58).

MongoDB then logs:
`new ssl connection, SNI server name [server]`

where `server` is the hostname.

When I'm using JRuby, the MongoDB log shows:
`new ssl connection, SNI server name []`

[Here](https://github.com/mongodb/mongo-ruby-driver/pull/815/files) is the relevant change to the MongoDB Ruby driver.

I've tried with JRuby 1.7.22 and 9.1.2.0.

Let me know if there something else I have to do to get SNI support from JRuby's openssl library. Thanks!

Emily
##

**Comment by headius** [comment] 2016-09-13 14:44
Perhaps there's SNI tests somewhere we could try to run? It's really troublesome to support openssl features when there's no tests for most of them :-(

**Comment by prcongithub** [comment] 2018-09-19 10:15
Any update here? I am trying to connect my JRuby 9.1.17.0 app to MongoDB Atlas with ```ssl: true```. It's not able to connect to servers. Same thing works with Ruby 2.2.3 app.

**Comment by prcongithub** [comment] 2018-09-21 08:54
@headius I am able to reproduce the issue with Ruby Mongo driver connecting to a TLS enabled MongoDB cluster.
```
jruby-9.1.15.0 :002 > client = Mongo::Client.new("mongodb+srv://admin:!J0mbay!@sqcluster0-rntvf.mongodb.net/test")
 => #<Mongo::Client:0x2148 cluster=sqcluster0-shard-00-00-rntvf.mongodb.net:27017, sqcluster0-shard-00-01-rntvf.mongodb.net:27017, sqcluster0-shard-00-02-rntvf.mongodb.net:27017>
jruby-9.1.15.0 :003 > client.list_databases
=> Mongo::Error::NoServerAvailable: No server is available matching preference: #<Mongo::ServerSelector::Primary:0x2162 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015
	from (irb):3:in `<eval>'
```
Do you need anything else? I can share a dummy username and password to connect with the real mongo cluster on MongoDB Atlas.

**Comment by prcongithub** [comment] 2018-09-21 09:20
@headius I am able to reproduce the issue with Ruby Mongo driver connecting to a TLS enabled MongoDB cluster.
```
jruby-9.1.15.0 :002 > client = Mongo::Client.new("mongodb+srv://<Username>:<Password>@sqcluster0-rntvf.mongodb.net/test")
 => #<Mongo::Client:0x2148 cluster=sqcluster0-shard-00-00-rntvf.mongodb.net:27017, sqcluster0-shard-00-01-rntvf.mongodb.net:27017, sqcluster0-shard-00-02-rntvf.mongodb.net:27017>
jruby-9.1.15.0 :003 > client.list_databases
=> Mongo::Error::NoServerAvailable: No server is available matching preference: #<Mongo::ServerSelector::Primary:0x2162 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015
	from (irb):3:in `<eval>'
```
Do you need anything else? I can share a dummy username and password to connect with the real mongo cluster on MongoDB Atlas.

**Comment by prcongithub** [comment] 2018-09-21 12:09
@estolfo Would it be safe to set hostname on the socket in a forked repo and use it to connect to MongoDB Atlas for now?

**Comment by estolfo** [comment] 2018-09-21 12:17
@prcongithub My apologies, I don't work on this project anymore. I suggest reaching out to @p-mongo or @saghm instead.

**Comment by p-mongo** [comment] 2018-09-25 22:03
SNI works with jruby 9.1.17.0 and 9.2.0.0 when using java 8.

We enabled it in https://github.com/mongodb/mongo-ruby-driver/commit/e7421ba7434f4d39d0b0b2324a1222d0b1eee7e6.

**Comment by kares** [comment] 2018-09-26 06:56
thanks Oleg, was pretty sure its already working, since Java 8 is the preferred stack this will stay as is.
also believe they also added the Java API in 8, so this will stay a wont fix for Java 7 users ...

**Comment by p-mongo** [comment] 2020-09-10 18:51
Should this ticket be closed? It looks like SNI is supported with java 8 and higher and not supported with java 7 and this is the desired behavior going forward.

**Closed** 2020-09-11 06:40 UTC
Labels: invalid
