### ISSUE TITLE
Error installing latest version

### ISSUE THREAD

**Issue by irfn** [jruby/jruby-openssl#152] opened 2017-11-27 13:12 UTC
i see that the naming of the gem releases have changed to have `-java` in the version.

somehow this is causing an issue with including this gem
Env: jruby:9.1.14.0 on docker

Scenario 1:

When i use the following in the Gemfile.
```
gem 'jruby-openssl', '0.9.21-java'
```

I get this following error
```
Could not find gem 'jruby-openssl (= 0.9.21.pre.java)' in any of the gem sources
listed in your Gemfile.
```

Scenario 2:

When i use the following in the Gemfile. (Omit version)
```
gem 'jruby-openssl'
```

Version 0.9.4 gets installed (this is also the same version listed by default on https://rubygems.org/gems/jruby-openssl/)

Scenario 3:
```
gem 'jruby-openssl', '0.9.21'
```

```
Could not find gem 'jruby-openssl (= 0.9.21)' in any of the gem sources listed
in your Gemfile.
```

**Comment by mkristian** [comment] 2017-11-27 14:33
jruby-openssl is java platform gem - which ruby are you using to install it ?

regarding rubygems.org showing the wrong version is expected behaviour https://github.com/rubygems/rubygems.org/issues/954#issuecomment-102419678 even though from the jruby-openssl it is not wanted.

**Comment by irfn** [comment] 2017-11-27 16:13
This is on a Docker image built from jruby:9.1.14.0 (https://hub.docker.com/_/jruby/)

i had to add this line to make this work
`gem 'jruby-openssl', '0.9.21', platform: :jruby`

**Comment by mkristian** [comment] 2017-11-27 18:41
if this is a jruby docker image I suspect that jruby is running `bundle install` and this should pick the right jruby-openssl by default.

**Comment by mkristian** [comment] 2017-11-28 07:48
just double check on regular jruby install it just picks the right and latest or second latest jruby-openssl version. question why is the bundled default jruby-openssl gem coming with jruby not sufficient ?

**Comment by irfn** [comment] 2017-11-28 16:33
@mkristian i am investigating a performance issue and was trying different versions of rails5.x/jruby and decided to pick specific versions and hence the need.
Agree that in the usual usecase one would not hit this issue. You can close this issue, since this thread will act as a guide for anyone else who runs into this issue.
Thanks for your support

**Comment by mkristian** [comment] 2017-11-28 18:30
@irfn closing but still bit puzzled that you ran into this problem as I could not reproduce it. could be still something on JRuby side to fix.

**Closed by mkristian** 2017-11-28 18:30 UTC
